project:
  type: book

book:
  title: "epijuliahandbook_eng"
  execute-dir: project
  output-dir: _book
  jupyter: julia-1.8


  repo-url: https://github.com/appliedepi/epiJuliahandbook_eng

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



