project:
  type: book
  # execute-dir: project
  output-dir: _book


published-title: "Last updated"
lightbox: true # Lightbox images allow a reader to click to see a larger version of the image (including any caption)

babelquarto:
  languagecodes:
  # - name: vn
  #   text: "Tiếng Việt"
  - name: en
    text: "English"

  mainlanguage: 'en'
  languages: [] 

# title-vn: "Cẩm nang dịch tễ học với R"


lang: en


book:
  title: "The Epidemiologist Julia Handbook"
  search:
    type: textbox
  repo-url: https://github.com/appliedepi/epiJuliahandbook_eng
  repo-actions: [issue]
  # site-url: https://epirhandbook.com
  sharing: ["twitter", "facebook", "linkedin"]
  sidebar:
    logo: "images/Applied_Epi_logo.png"
    tools:
      - icon: twitter
        href: "https://twitter.com/appliedepi"
      - icon: linkedin
        href: "https://www.linkedin.com/company/appliedepi/"
  page-footer:
    left: |
      The Epidemiologist Julia Handbook was written by Applied Epi
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cookie-consent:
    type: express
    style: simple
  google-analytics:
    tracking-id: "G-XXXXXXX"
  date: today
  date-format: "MMM D, YYYY"
  favicon: "images/Applied_Epi_logo.png"


  chapters:
  # INTRO & CONTRIBUTORS
  - index.qmd                              # objectives, how to read, authors, acknowledgements

  # ABOUT BOOK
  - part: "About this book"
    # part-vn: "Về cuốn sách này" 

    chapters:
    - pages/editorial_style.qmd          # editorial style
    - pages/data_used.qmd                # data used

  # BASICS
  - part: "Basics"
    # part-vn: "Nhập môn về R"

    chapters:
    - pages/basics.qmd
    - pages/transition_to_R.qmd
    - pages/packages_suggested.qmd
    - pages/r_projects.qmd
    - pages/importing.qmd

  # DATA MANAGEMENT
  - part: "Data Management"
    # part-vn: "Quản lý dữ liệu"

    chapters:
    - pages/cleaning.qmd
    - pages/dates.qmd
    - pages/characters_strings.qmd
    - pages/factors.qmd
    - pages/pivoting.qmd
    - pages/grouping.qmd
    - pages/joining_matching.qmd
    - pages/deduplication.qmd
    - pages/iteration.qmd

  # ANALYSIS
  - part: "Analysis"
    # part-vn: "Phân tích dữ liệu"

    chapters:
    - pages/tables_descriptive.qmd
    - pages/stat_tests.qmd
    - pages/regression.qmd
    - pages/missing_data.qmd
    - pages/standardization.qmd
    - pages/moving_average.qmd
    - pages/time_series.qmd #done
    - pages/epidemic_models.qmd #done
    - pages/contact_tracing.qmd #done
    - pages/survey_analysis.qmd #done
    - pages/survival_analysis.qmd #done
    - pages/gis.qmd #done

  # DATA VIZ
  - part: "Data Visualization"
    # part-vn: "Trực quan hóa dữ liệu"

    chapters:
    - pages/tables_presentation.qmd  
    - pages/ggplot_basics.qmd
    - pages/ggplot_tips.qmd 
    - pages/epicurves.qmd 
    - pages/age_pyramid.qmd 
    - pages/heatmaps.qmd   
    - pages/diagrams.qmd  
    - pages/combination_analysis.qmd 
    - pages/transmission_chains.qmd 
    - pages/phylogenetic_trees.qmd 
    - pages/interactive_plots.qmd 

  # REPORTS AND DASHBOARDS
  - part: "Reports and dashboards"
    # part-vn: "Báo cáo và dashboards"

    chapters:
    - pages/rmarkdown.qmd 
    - pages/reportfactory.qmd 
    - pages/flexdashboard.qmd 
    - pages/shiny_basics.qmd 

  # MISCELLANEOUS
  - part: "Miscellaneous"
    # part-vn: "Các chủ điểm khác"

    chapters:
    - pages/writing_functions.qmd 
    - pages/directories.qmd 
    - pages/collaboration.qmd 
    - pages/errors.qmd 
    - pages/help.qmd 
    - pages/network_drives.qmd 
    - pages/data_table.qmd 

bibliography: pages/references.bib

format:
  html: 
    include-in-header:
      - banner.html
    theme:
      light: cosmo
      dark: [darkly, theme-dark.scss]



